config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  resources :categories, only: %i[index show create new destroy update] do
    resources :transancts, only: %i[index show create new destroy update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :category_transancts, dependent: :destroy
  has_many :transancts, through: :category_transancts, dependent: :destroy

  validates_presence_of :user
  validates :name, presence: true, length: { maximum: 30 }
  validates :icon, presence: true
end

app/models/category_transanct.rb
class CategoryTransanct < ApplicationRecord
  belongs_to :category
  belongs_to :transancts
end

app/models/transancts.rb
class Transancts < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :category_transancts, dependent: :destroy
  has_many :categories, through: :category_transancts, dependent: :destroy
  validates_presence_of :user
  validates :name, presence: true, length: { maximum: 30 }
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :transancts, foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories
  end

  def show
    @category = current_user.categories.find(params[:id])
    @transancts = @category.transancts
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.create(category_params)
    if @category.save

      redirect_to categories_path
    else
      flash[:alert] = 'All fields are required'
      render :new
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @Category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/categories_controllers.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories
  end

  def show
    @category = current_user.categories.find(params[:id])
    @transancts = @category.transancts
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.create(category_params)
    if @category.save

      redirect_to categories_path
    else
      flash[:alert] = 'All fields are required'
      render :new
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @Category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/transancts_controller.rb
class TransanctsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transact, only: %i[show edit update destroy]

  def index
    @transancts = current_user.categories.find(params[:category_id]).transancts.order(created_at: :desc)
    @category = current_user.categories.find(params[:category_id])
  end

  def show
    @transancts = current_user.categories.find(params[:category_id]).transancts.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @transanct = Transancts.new
  end

  def create
    @transanct = Transancts.new(transancts_params)
    @transanct.user = current_user
    @category = Category.find(params[:category_id])
    @category.transancts << @transanct if @transanct.save

    if @transanct.save
      redirect_to category_transancts_path(params[:category_id])
    else
      flash[:alert] = 'All fields are required'
      render :new
    end
  end

  def destroy
    @transac = current_user.categories.find(params[:category_id]).transancts.find(params[:transac_id])
    @transac.destroy
    redirect_to category_transancts_path(@transac.category_id)
  end

  private

  def set_transact
    @transanct = Transancts.find(params[:id])
  end

  def transancts_params
    params.require(:transancts).permit(:amount, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transancts_helper.rb
module TransanctsHelper
end

app/views/Home/index.html.erb
<section class="flex flex-col justify-center gap-y-8 items-center h-screen">

    <h1 class="home-title text-slate-500 mb-4 text-[48px] font-bold text-sky-700">BUDGET APP</h1>
    <div class="w-[20rem] flex-col flex text-center font-bold">
    <%= link_to new_user_session_path, class: "" do %>
          <div class="w-full bg-sky-600 home px-8 py-4 mb-4 rounded-lg cursor-pointer hover:bg-sky-700">
               <h2>LOGIN</h2>
          </div>
     <% end %>
     <%= link_to new_user_registration_path do %>
          <div class="w-full bg-sky-600 home px-8 py-4 rounded-lg cursor-pointer hover:bg-sky-700">
               <h2>SIGNUP</h2>
          </div>
     <% end %>
    </div>
</section>

app/views/categories/index.html.erb
<section class="category h-screen">
<header class="header bg-sky-600 text-white font-bold">
     <div>
      <p class="text-2xl">💰</p>
    </div>
    <h2 class= "justify-self-center">CATEGORIES</h2>
    <div>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "sign_out text_white" %>
    </div>
</header>

<ul class="ul mx-auto overflow-y-auto overflow-x-hidden list">
    <% if @categories.length == 0 %>
        <p class="text-center">No categories yet</p>
    <% else %>
    <% @categories.each do |category| %>
     <%= link_to category_transancts_path(category), class: '' do %>
        <li class="list bg margin-bottom">
                <img src="<%= category.icon %>" class="image"/>
                <div class="text-secondary ml-2 p-2">
                    <p class="name"><%= category.name %></p>
                    <p class="smal-txt"><%= category.created_at.strftime("%d %b %Y") %> </p>
                </div>
                <div class="amount">
                    <%= number_to_currency(category.transancts.sum(:amount))%>
                </div>
        </li>
     <% end %>
    <% end %>
    <% end %>
</ul>

<div class="flex justify-center items-center bg-sky-600 text-white py-5 px-3 font-bold">
    
      <%= link_to "ADD NEW CATEGORY", new_category_path(@category,current_user),  class:"add-button cursor-pointer hover:bg-sky-700" %>
</div>
</section>

app/views/categories/new.html.erb
<section class="category h-screen">
<header class="header bg-sky-600 font-bold">
    <div class="back">
    <%= link_to categories_path, class: "text-xl border border-2 p-2 text-xl back" do %>
        <span class="text-2xl">&#8701;</span>
    <% end %>
  </div>
    <h2 class= "justify-self-center">NEW CATEGORY</h2>
    <div>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "sign_out text_white" %>
    </div>
</header>
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %> 
 <%= form_with(model: @category, url: { action: "create" }, class: "border-top border-2 mx-auto flex flex-col justify-between gap-y-5 margin-bottom") do |form| %>
  <div class="field">
    <%= form.text_field :name, placeholder: "Enter the category's name", class: "width margin-bottom" %>
  </div>
  <div class="field">
    <%= form.text_field :icon, autofocus: true, placeholder: "Enter the image url", type:'url', autocomplete: "", class: "width margin-bottom"%>
  </div>
  <div>
  <%= form.submit "SAVE", class:"button font-bold width cursor-pointer" %>
  </div>
<% end %>
<div class="footer bg-sky-600  font-bold">
    <h2>@DavidLyangenda</h2>
</div>
</section>

app/views/categories/show.html.erb
<section class="categories">
<header class="d-flex justify-content-between align-items-center bg-primary text-white py-2 px-3">
     <div>
        <%= link_to root_path, class: "text-white" do %>
            <i class="fa fa-bars" aria-hidden="true"></i>
        <% end %>
    </div>
    <h2 class= "justify-self-center">TRANSANCTION</h2>
    <div>
    <%= link_to destroy_user_session_path, class:'text-white', :method => :delete do %>
         <i class="fas fa-sign-out-alt "></i>
    <% end %>
    </div>
  </header>

<img src="<%= @category.icon %>" class="h-75 rounded"/>
<div class="bg-white py-4 px-2">
   <%= @category.name %>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>

    <div id="flashes">
      <% flash.each do |type, msg| %>
        <div class="alert">
          <%= msg %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/transancts/create.html.erb
<h1>Create a new transanction</h1>

app/views/transancts/index.html.erb
<div class="category h-screen">
<div>
<header class="header bg-sky-600 font-bold">
     <div class="back">
    <%= link_to categories_path, class: "text-xl border border-2 p-2 text-xl back" do %>
        <span class="text-2xl">&#8701;</span>
    <% end %>
  </div>
    <h2 class= "justify-self-center">Transanctions</h2>
    <div>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "sign_out text_white" %>
    </div>
</header>
<div class="bg py-4 px-2 text-center margin-bottom">
   Total amount: <span class="fw-bold"> <%= number_to_currency(@category.transancts.sum(:amount)) %></span>
</div>
</div>
<ul class="ul mx-auto gap-y-2 overflow-y-auto overflow-x-hidden list">
  <% if @transancts.length == 0 %>
         <p class="text-center text-slate-800">No transactions created yet</p>
   <% else %>
    <%  @transancts.each do |transanct| %>
        <li class="list bg margin-bottom trans">
                <div>
                    <p class="name"><%= transanct.name %></p>
                    <p class="smal-txt text-secondary"><%= transanct.created_at.strftime("%d %B %Y") %> at <%= transanct.created_at.strftime("%H:%M") %></p>
                </div>                              
                <div class="my-2">
                     <span class="fw-bold"> <%= number_to_currency(transanct.amount) %></span>
                </div>
        </li>
    <% end %>
    <%end%>
</ul>

<div class="flex justify-center items-center bg-sky-600 text-white py-5 px-3 font-bold">
    <%= link_to "ADD NEW TRANSANCTION", new_category_transanct_path(@category),  class:"add-button cursor-pointer hover:bg-sky-700" %>
</div>
</div>

app/views/transancts/new.html.erb
<section class="category h-screen">

  <header class="header bg-sky-600 font-bold">
    <div class="back">
      <%= link_to categories_path, class: "text-xl border border-2 p-2 text-xl back" do %>
          <span class="text-2xl">&#8701;</span>
      <% end %>
    </div>
    <h2 class= "justify-self-center">NEW TRANSANCTION</h2>
    <div>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "sign_out text_white" %>
    </div>
  </header>
  
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %> 
 
 <%= form_with(model: @transanct, url: {action: "create" }, class:"border-top border-2 mx-auto flex flex-col justify-between gap-y-5 margin-bottom") do |form| %>
  <div class="field">
    <%= form.text_field :name, autofocus: true, placeholder: "Name", autocomplete: "", class: "width margin-bottom"%>
  </div>

  <div class="field">
    <%= form.text_field :amount, placeholder: "Amount", class: "width margin-bottom" %>
  </div>
    
  <div>
    <%= form.submit "SAVE", class:"button font-bold width cursor-pointer"  %>
  </div>
<% end %>
<div class="footer bg-sky-600 font-bold">
    <h2>@ciraganenicole</h2>
</div>

</section>

app/views/transancts/show.html.erb
<h1>Single transanction</h1>